import { useMemo, useState } from "react";
import { CarProfile, CaretLeft, MagnifyingGlass, SlidersHorizontal } from "@phosphor-icons/react";
import { VehicleRow } from "./vehicle-row";
import type { Vehicle } from "@/src/types/vehicle";

interface Props { vehicles: Vehicle[]; selectedId?: string; query: string; onQueryChange: (value: string) => void; onSelect: (vehicle: Vehicle) => void; isLoading: boolean; error: string | null; onRetry: () => void }
export function VehicleDrawer({ vehicles, selectedId, query, onQueryChange, onSelect, isLoading, error, onRetry }: Props) {
  const [sort, setSort] = useState<"state" | "speed" | "group">("state"); const [ascending, setAscending] = useState(false);
  const sorted = useMemo(() => [...vehicles].sort((a,b) => { const result = sort === "speed" ? a.speed - b.speed : sort === "group" ? a.group.localeCompare(b.group, "ar") : a.state.localeCompare(b.state); return ascending ? result : -result; }), [vehicles, sort, ascending]);
  return <section className="vehicle-drawer glass"><header><div className="drawer-title"><div className="round-icon"><CarProfile weight="duotone" /></div><div><h2>المركبات</h2><span><i/> متابعة مباشرة</span></div></div><button className="drawer-sort-button" onClick={() => setAscending((v) => !v)} aria-label="عكس الترتيب"><CaretLeft style={{ transform: ascending ? "rotate(90deg)" : "rotate(-90deg)" }} /></button></header><label className="drawer-search"><MagnifyingGlass weight="duotone"/><input value={query} onChange={(e) => onQueryChange(e.target.value)} placeholder="ابحث بالاسم أو السائق..." /><SlidersHorizontal weight="duotone"/></label><div className="filter-tabs"><button className={sort === "state" ? "active" : ""} onClick={() => setSort("state")}>الحالة</button><button className={sort === "speed" ? "active" : ""} onClick={() => setSort("speed")}>السرعة</button><button className={sort === "group" ? "active" : ""} onClick={() => setSort("group")}>القسم</button><button onClick={() => setAscending((v) => !v)} aria-label="عكس الترتيب"><SlidersHorizontal weight="duotone"/></button></div><div className="group-label"><span>كل المركبات</span><b>{vehicles.length}</b></div><div className="vehicle-list">{isLoading ? <div className="drawer-feedback">جاري تحميل المركبات...</div> : error ? <div className="drawer-feedback"><span>{error}</span><button onClick={onRetry}>إعادة المحاولة</button></div> : sorted.length ? sorted.map((v) => <VehicleRow key={v.id} vehicle={v} selected={v.id === selectedId} onClick={() => onSelect(v)} />) : <div className="drawer-feedback">لا توجد نتائج مطابقة</div>}</div><footer><span>{vehicles.length} مركبات</span><div><i className="dot green" />{vehicles.filter(v => v.state === "moving").length} متحركة <i className="dot yellow" />{vehicles.filter(v => v.state === "idle").length} خاملة <i className="dot pink" />{vehicles.filter(v => v.state === "stopped").length} متوقفة</div></footer></section>;
}
