import { useState } from "react";
import { ArrowsClockwise, Crosshair, GlobeHemisphereWest, ListBullets, Moon, Sparkle, Sun } from "@phosphor-icons/react";

export function TopBar({ onMenuOpen }: { onMenuOpen: () => void }) {
  const [light, setLight] = useState(false); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const toggleTheme = () => { setLight((value) => { document.documentElement.classList.toggle("light-theme", !value); return !value; }); };
  const search = () => { if (!query.trim()) return; setMessage(`جاري البحث عن: ${query}`); window.setTimeout(() => setMessage(""), 2000); };
  return <><header className="top-bar"><div className="brand"><div className="brand-orb"><GlobeHemisphereWest weight="duotone"/><span className="brand-spark"><Sparkle weight="fill"/></span></div><div className="brand-copy"><b>ORBIT</b><small>FLEET INTELLIGENCE</small></div><button className="theme-button premium-icon-button" onClick={toggleTheme} aria-label="تغيير المظهر">{light ? <Moon weight="duotone"/> : <Sun weight="duotone"/>}</button></div><label className="global-search"><span className="search-icon"><Crosshair weight="duotone"/></span><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && search()} placeholder="ابحث عن مركبة، سائق أو موقع..." /><kbd>⌘ K</kbd></label><div className="top-left"><button className="menu-button" onClick={onMenuOpen} aria-label="فتح القائمة"><ListBullets /></button><div className="sync-copy"><span>النظام متصل</span><small>تمت المزامنة الآن</small></div><button className="signal premium-icon-button" onClick={() => { setMessage("تمت مزامنة البيانات"); window.setTimeout(() => setMessage(""), 2000); }} aria-label="مزامنة"><ArrowsClockwise size={17}/><i /></button></div></header>{message && <div className="toast top-toast">{message}</div>}</>;
}
