import type { EntityFormSchema } from "@/src/types/entity";
import type { PageId } from "@/src/types/navigation";

const status = [{ label: "نشط", value: "active" }, { label: "يحتاج انتباه", value: "attention" }, { label: "غير نشط", value: "inactive" }];
const deviceOptions = [{ label: "2410ASA RUHTCS", value: "2410ASA RUHTCS" }, { label: "2414ASA RUHTCS", value: "2414ASA RUHTCS" }, { label: "2447ASA RUHOPS", value: "2447ASA RUHOPS" }, { label: "7926 BXA JEDTCS", value: "7926 BXA JEDTCS" }];
const schema = (singular: string, primaryKey: string, secondaryKey: string, fields: EntityFormSchema["fields"]): EntityFormSchema => ({ singular, primaryKey, secondaryKey, fields: [...fields, { key: "status", label: "الحالة", type: "select", optionCategory:"record_status", options: status, required: true }, { key: "notes", label: "ملاحظات", type: "textarea", wide: true }] });

export const entityForms: Record<PageId, EntityFormSchema> = {
  home: schema("مؤشر", "name", "details", [{ key: "name", label: "اسم المؤشر", type: "text", required: true }, { key: "details", label: "القيمة", type: "text", required: true }]),
  live: schema("مركبة", "name", "device", [{ key: "name", label: "اسم المركبة", type: "text", required: true }, { key: "device", label: "الجهاز", type: "select", optionCategory:"vehicle", options: deviceOptions }]),
  vehicles: schema("مركبة", "name", "group", [{ key: "name", label: "الاسم / لوحة المركبة", type: "text", placeholder: "2414ASA RUHTCS", required: true }, { key: "imei", label: "IMEI الجهاز", type: "text", required: true }, { key: "sim", label: "رقم شريحة SIM", type: "tel" }, { key: "group", label: "المجموعة", type: "select", optionCategory:"vehicle_group", options: [{ label: "ليست في مجموعة", value: "ليست في مجموعة" }, { label: "RUHTCS", value: "RUHTCS" }, { label: "RUHOPS", value: "RUHOPS" }, { label: "JEDTCS", value: "JEDTCS" }] }, { key: "plate", label: "رقم اللوحة", type: "text" }, { key: "driver", label: "السائق", type: "text" }, { key: "expiry", label: "تاريخ انتهاء الصلاحية", type: "date" }]),
  drivers: schema("سائق", "name", "devices", [{ key: "name", label: "الاسم", type: "text", placeholder: "إدراج الاسم...", required: true }, { key: "devices", label: "الأجهزة", type: "select", options: deviceOptions, required: true }, { key: "current", label: "تعيين كسائق حالي", type: "checkbox" }, { key: "rfid", label: "بطاقة السائق RFID", type: "text", placeholder: "إدراج بطاقة السائق RFID..." }, { key: "email", label: "البريد الإلكتروني", type: "email", placeholder: "إدراج البريد الإلكتروني..." }, { key: "phone", label: "الهاتف", type: "tel", placeholder: "إدراج هاتف..." }, { key: "description", label: "الوصف", type: "textarea", wide: true }]),
  tasks: schema("مهمة", "title", "device", [{ key: "device", label: "الجهاز", type: "select", options: deviceOptions, required: true }, { key: "title", label: "العنوان", type: "text", placeholder: "إدراج العنوان...", required: true }, { key: "invoice", label: "رقم الفاتورة", type: "text", placeholder: "إدراج رقم الفاتورة..." }, { key: "priority", label: "الأولوية", type: "select", options: [{ label: "أولوية منخفضة", value: "منخفضة" }, { label: "أولوية عادية", value: "عادية" }, { label: "أولوية مرتفعة", value: "مرتفعة" }] }, { key: "pickupAddress", label: "عنوان الاستلام", type: "text", required: true }, { key: "pickupTime", label: "وقت الاستلام", type: "datetime-local" }, { key: "deliveryAddress", label: "عنوان التسليم", type: "text", required: true }, { key: "deliveryTime", label: "موعد التسليم", type: "datetime-local" }, { key: "autoStatus", label: "تغيير الحالة تلقائيًا", type: "checkbox" }, { key: "comment", label: "تعليق", type: "textarea", wide: true }]),
  history: schema("رحلة", "route", "device", [{ key: "device", label: "الجهاز", type: "select", options: deviceOptions, required: true }, { key: "route", label: "المسار", type: "text", required: true }, { key: "from", label: "من", type: "datetime-local" }, { key: "to", label: "إلى", type: "datetime-local" }]),
  geofences: schema("نطاق جغرافي", "name", "type", [{ key: "name", label: "اسم النطاق", type: "text", required: true }, { key: "group", label: "المجموعة", type: "text" }, { key: "type", label: "نوع الرسم", type: "select", options: [{ label: "دائرة", value: "دائرة" }, { label: "مضلع", value: "مضلع" }], required: true }, { key: "address", label: "الموقع / العنوان", type: "text", required: true }, { key: "radius", label: "نصف القطر بالمتر", type: "number" }, { key: "color", label: "لون النطاق", type: "color" }]),
  alerts: schema("تنبيه", "name", "eventType", [{ key: "name", label: "اسم التنبيه", type: "text", required: true }, { key: "eventType", label: "نوع الحدث", type: "select", options: [{ label: "تجاوز السرعة", value: "تجاوز السرعة" }, { label: "دخول نطاق", value: "دخول نطاق" }, { label: "خروج من نطاق", value: "خروج من نطاق" }, { label: "مدة التوقف", value: "مدة التوقف" }, { label: "SOS", value: "SOS" }] }, { key: "device", label: "الجهاز", type: "select", options: deviceOptions }, { key: "limit", label: "القيمة / الحد", type: "number" }, { key: "email", label: "بريد الإشعار", type: "email" }]),
  cameras: schema("كاميرا", "name", "device", [{ key: "name", label: "اسم الكاميرا", type: "text", required: true }, { key: "device", label: "المركبة", type: "select", options: deviceOptions, required: true }, { key: "cameraType", label: "الموضع", type: "select", options: [{ label: "أمامية", value: "أمامية" }, { label: "داخلية", value: "داخلية" }, { label: "خلفية", value: "خلفية" }] }, { key: "streamUrl", label: "رابط البث", type: "text" }]),
  maintenance: schema("خدمة صيانة", "serviceName", "vehicle", [{ key: "serviceId", label: "هوية الخدمة", type: "text", required: true }, { key: "serviceName", label: "اسم الخدمة", type: "text", required: true }, { key: "vehicle", label: "المركبة", type: "select", options: deviceOptions, required: true }, { key: "distance", label: "المسافة (كم)", type: "number" }, { key: "engineHours", label: "ساعات المحرك", type: "number" }, { key: "days", label: "الأيام", type: "number" }, { key: "lastService", label: "تاريخ آخر صيانة", type: "date" }]),
  fuel: schema("عملية وقود", "vehicle", "liters", [{ key: "vehicle", label: "المركبة", type: "select", options: deviceOptions, required: true }, { key: "date", label: "التاريخ", type: "datetime-local", required: true }, { key: "liters", label: "الكمية (لتر)", type: "number", required: true }, { key: "cost", label: "التكلفة", type: "number" }, { key: "odometer", label: "عداد المسافة", type: "number" }, { key: "station", label: "المحطة", type: "text" }, { key: "invoice", label: "رقم الفاتورة", type: "text" }]),
  reports: schema("تقرير", "reportName", "reportType", [{ key: "reportName", label: "اسم التقرير", type: "text", required: true }, { key: "reportType", label: "نوع التقرير", type: "select", optionCategory:"report_type", options: [{ label: "الحركة والتوقف", value: "الحركة والتوقف" }, { label: "المسافة", value: "المسافة" }, { label: "الوقود", value: "الوقود" }, { label: "التنبيهات", value: "التنبيهات" }, { label: "المهام", value: "المهام" }] }, { key: "device", label: "الجهاز", type: "select", optionCategory:"vehicle", options: deviceOptions }, { key: "from", label: "من", type: "datetime-local" }, { key: "to", label: "إلى", type: "datetime-local" }, { key: "format", label: "الصيغة", type: "select", optionCategory:"report_format", options: [{ label: "PDF", value: "PDF" }, { label: "Excel", value: "Excel" }, { label: "CSV", value: "CSV" }] }]),
  settings: schema("قيمة إعداد", "name", "details", [{key:"name",label:"الاسم",type:"text",required:true},{key:"details",label:"القيمة",type:"text",required:true}]),
};
