import { useState } from "react";
import { FloppyDisk, X } from "@phosphor-icons/react";
import type { EntityFormSchema, EntityRecord } from "@/src/types/entity";
import type { ConfigurationGroups } from "@/src/services/configuration.service";
import { useFormOptions } from "@/src/hooks/use-form-options";

interface Props { title:string; schema:EntityFormSchema; options?:ConfigurationGroups; record?:EntityRecord; onClose:()=>void; onSave:(record:EntityRecord)=>void }
const categoryFor=(title:string,key:string)=>key==="status"?"record_status":["device","devices","vehicle"].includes(key)?"vehicle":key==="priority"?"task_priority":key==="eventType"?"alert_type":key==="cameraType"?"camera_position":key==="serviceName"?"maintenance_service":key==="reportType"?"report_type":key==="format"?"report_format":key==="type"&&title.includes("الجغرافية")?"geofence_type":key==="group"&&title.includes("المركبات")?"vehicle_group":undefined;

export function EntityModal({title,schema,options={},record,onClose,onSave}:Props){
  const loadedOptions=useFormOptions();options={...loadedOptions,...options};
  const initial=record?.metadata??{name:record?.name??"",details:record?.details??"",status:record?.status??"active",notes:record?.notes??"",color:"#28e1da"};
  const [values,setValues]=useState<Record<string,string>>(initial);
  const update=(key:string,value:string)=>setValues(current=>({...current,[key]:value}));
  const requiredComplete=schema.fields.filter(field=>field.required).every(field=>values[field.key]?.trim());
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="entity-modal entity-modal--wide glass" role="dialog" aria-modal="true"><header><div><small>{record?"تعديل البيانات":"إضافة جديدة"}</small><h2>{schema.singular} — {title}</h2></div><button onClick={onClose} aria-label="إغلاق"><X/></button></header><div className="form-grid">{schema.fields.map(field=>{const category=field.optionCategory??categoryFor(title,field.key);const fieldOptions=category&&options[category]?.length?options[category]:field.options;const isSelect=field.type==="select"||Boolean(category&&options[category]?.length);return <label key={field.key} className={`${field.wide?"full":""} ${field.type==="checkbox"?"check-field":""}`}><span>{field.label}{field.required&&" *"}</span>{isSelect?<select value={values[field.key]??""} onChange={e=>update(field.key,e.target.value)}><option value="">اختر...</option>{fieldOptions?.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.type==="textarea"?<textarea value={values[field.key]??""} onChange={e=>update(field.key,e.target.value)} placeholder={field.placeholder}/>:field.type==="checkbox"?<input type="checkbox" checked={values[field.key]==="true"} onChange={e=>update(field.key,String(e.target.checked))}/>:<input type={field.type} value={values[field.key]??""} onChange={e=>update(field.key,e.target.value)} placeholder={field.placeholder}/>}</label>})}</div><footer><button onClick={onClose}>إلغاء</button><button className="save-button" disabled={!requiredComplete} onClick={()=>onSave({id:record?.id||crypto.randomUUID(),name:values[schema.primaryKey]||schema.singular,details:values[schema.secondaryKey]||"—",updatedAt:"الآن",status:(values.status as EntityRecord["status"])||"active",notes:values.notes,metadata:values})}><FloppyDisk/> حفظ البيانات</button></footer></section></div>;
}
